# Generated by Django 4.1.7 on 2023-02-21 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100, null=True)),
                ("student_id", models.IntegerField(verbose_name="student id")),
                ("grad_year", models.IntegerField(verbose_name="graduation year")),
                (
                    "hours_remaining",
                    models.IntegerField(verbose_name="hours remaining"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, null=True)),
                ("event_date", models.DateTimeField(verbose_name="event date")),
                (
                    "num_registered",
                    models.IntegerField(null=True, verbose_name="num registered"),
                ),
                ("students", models.ManyToManyField(to="registration.student")),
            ],
        ),
    ]
