# Generated by Django 4.1.7 on 2023-02-20 20:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("event_date", models.DateTimeField(verbose_name="date of event")),
                ("num_registered", models.DateField(verbose_name="num registered")),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("student_id", models.IntegerField(verbose_name="student id")),
                ("grad_year", models.IntegerField(verbose_name="graduation year")),
                (
                    "hours_remaining",
                    models.IntegerField(verbose_name="hours remaining"),
                ),
            ],
        ),
    ]
