# Generated by Django 4.1.7 on 2023-02-20 20:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_date",
            field=models.DateTimeField(verbose_name="event date"),
        ),
        migrations.AlterField(
            model_name="event",
            name="num_registered",
            field=models.IntegerField(verbose_name="num registered"),
        ),
    ]
