# Generated by Django 4.1.7 on 2023-02-21 19:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="students",
        ),
    ]
