# Generated by Django 4.1.7 on 2023-02-20 20:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="email",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="teacher",
            name="email",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
