# Generated by Django 4.1.7 on 2023-02-21 19:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0002_remove_event_students"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="students",
            field=models.ManyToManyField(to="registration.student"),
        ),
    ]
