# Generated by Django 4.1.7 on 2023-02-20 20:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0002_student_email_teacher_email"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Person",
        ),
    ]
