# Generated by Django 4.1.7 on 2023-02-23 14:31

from django.db import migrations, models
import registration.models


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0003_event_students"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="name",
            new_name="event_name",
        ),
        migrations.RemoveField(
            model_name="event",
            name="students",
        ),
        migrations.AddField(
            model_name="event",
            name="event_description",
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="event_pic_upload",
            field=models.ImageField(
                null=True, upload_to=registration.models.user_directory_path
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="is_recurring",
            field=models.BooleanField(default=False, verbose_name="is recurring"),
        ),
        migrations.AddField(
            model_name="event",
            name="logo_upload",
            field=models.ImageField(
                null=True, upload_to=registration.models.user_directory_path
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="num_students_needed",
            field=models.IntegerField(default=0, verbose_name="num needed"),
        ),
        migrations.AddField(
            model_name="event",
            name="organization_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="student_contact_id",
            field=models.IntegerField(null=True, verbose_name="student contact"),
        ),
        migrations.AddField(
            model_name="event",
            name="students_registered",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_date",
            field=models.DateTimeField(null=True, verbose_name="event date"),
        ),
        migrations.AlterField(
            model_name="event",
            name="num_registered",
            field=models.IntegerField(default=0, verbose_name="num registered"),
        ),
    ]
