# Generated by Django 4.1.7 on 2023-03-01 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0003_event_students"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="name",
            new_name="event_name",
        ),
        migrations.RenameField(
            model_name="event",
            old_name="students",
            new_name="students_registered",
        ),
        migrations.AddField(
            model_name="event",
            name="advisor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="registration.teacher",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="event_description",
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="event_pic_upload",
            field=models.ImageField(
                null=True, upload_to="images/event_image/", verbose_name="event_image"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="event_times",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="is_recurring",
            field=models.BooleanField(default=False, verbose_name="is recurring"),
        ),
        migrations.AddField(
            model_name="event",
            name="logo_upload",
            field=models.ImageField(
                null=True, upload_to="images/logo/", verbose_name="logo"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="num_required",
            field=models.IntegerField(default=0, verbose_name="num required"),
        ),
        migrations.AddField(
            model_name="event",
            name="organization_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="recursion_type",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="student_lead",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_lead",
                to="registration.student",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_date",
            field=models.DateTimeField(null=True, verbose_name="event date"),
        ),
        migrations.AlterField(
            model_name="event",
            name="num_registered",
            field=models.IntegerField(default=0, verbose_name="num registered"),
        ),
    ]
