# Generated by Django 4.1.7 on 2023-02-23 16:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "registration",
            "0004_rename_name_event_event_name_remove_event_students_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="event_times",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="recursion_type",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
