# Generated by Django 4.1.7 on 2023-03-02 01:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0005_rename_event_date_event_event_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_duration",
            field=models.TimeField(
                default=None, null=True, verbose_name="event duration"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_end_time",
            field=models.TimeField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_time",
            field=models.DateTimeField(
                default=None, null=True, verbose_name="event date"
            ),
        ),
    ]
