# Generated by Django 4.1.7 on 2023-03-03 19:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0006_alter_event_event_duration_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="gender",
            field=models.CharField(max_length=6, null=True),
        ),
    ]
