# Generated by Django 4.1.7 on 2023-03-06 19:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0007_teacher_gender"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="num_registered",
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("students", models.ManyToManyField(to="registration.student")),
            ],
        ),
    ]
