# Generated by Django 4.1.7 on 2023-04-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0009_event_hours_rewarded"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="hours_remaining",
            field=models.FloatField(verbose_name="hours remaining"),
        ),
    ]
